Add new hexstickers
Appsilon/shiny.tools pull request #12
Opened 2021-06-14 08:29 UTC by jchojna

- shiny.react
- shiny.fluent
- data.validator

2021-06-14 10:10 UTC, MicahAppsilon commented on app/scripts/libraries.js
> +      'We believe that a great UI plays a huge role in the success of application projects. shiny.fluent gives your apps beautiful and professional look, rich set of components easily usable in Shiny
```suggestion
      'We believe that a great UI plays a huge role in the success of application projects. shiny.fluent gives your apps a beautiful and professional look, rich set of easy-to-use components in Shiny, and fast speed of development that Shiny is famous for.',
```

2021-06-14 11:13 UTC, przytu1 requested changes
Code looks good! @jchojna please address @MicahAppsilon comments, push the update, and then you can merge :heavy_check_mark:

2021-06-15 05:22 UTC, merged

2021-06-15 05:30 UTC, jchojna commented on app/scripts/libraries.js
> +      'This R package enables using React in Shiny apps and is used e.g. by the shiny.fluent package. It contains R and JS code which is independent from the React library (e.g. Fluent UI) that is be
fixes

2021-06-15 05:30 UTC, jchojna commented on app/scripts/libraries.js
> +      'We believe that a great UI plays a huge role in the success of application projects. shiny.fluent gives your apps beautiful and professional look, rich set of components easily usable in Shiny
fixed